### ISSUE TITLE
Adding a readme?

### ISSUE THREAD

**Issue by PStellmann** [dita-ot/registry#12]
I think it would be good to provide a basic readme file - at least containing a link to the documentation: http://www.dita-ot.org/dev/topics/plugins-registry.html

And also note that the suggested way of generating the hash on windows (Get-FileHash <plugin-file> | Format-List) didn't work for me. I used "certutil -hashfile <plugin-file> SHA512" instead.

**Comment by infotexture** [comment]
@PStellmann Yes, a ReadMe is definitely necessary _(and planned)_, just didn't get to it in time for the 3.2 release.

_Coming soon…_

**Comment by infotexture** [comment]
Adding a screenshot of the registry here to generate a `user-images.githubusercontent.com` URL for use in the ReadMe (rather than adding the image to the repo itself).

![dita-ot-org-plugins_2048](https://user-images.githubusercontent.com/129995/48142257-bee91a00-e2ac-11e8-877e-827d2471fec6.png)
