### ISSUE TITLE
org.doctales.xmltask can't be installed through registry

### ISSUE THREAD

**Issue by pflotscher** [dita-ot/registry#135]
The sources of `org.doctales.xmltask` have been moved and the checksum changed. An install command gives the following output which shows the changes that need to be made to fix the bug:  

```
install:
  [install] Reading registries for org.doctales.xmltask@null
  [install] Read registry https://plugins.dita-ot.org/
  [install] Parse registry
  [install] Plugin found at https://plugins.dita-ot.org/org.doctales.xmltask.json@1.16.1
      [get] Getting: https://github.com/doctales/org.doctales.xmltask/archive/1.16.1.zip
      [get] To: /tmp/4788761146551753050/plugin.zip
      [get] https://github.com/doctales/org.doctales.xmltask/archive/1.16.1.zip permanently moved to https://github.com/stefan-jung/org.jung.xmltask/archive/1.16.1.zip
      [get] https://github.com/stefan-jung/org.jung.xmltask/archive/1.16.1.zip moved to https://codeload.github.com/stefan-jung/org.jung.xmltask/zip/refs/tags/1.16.1
Error: Downloaded plugin file checksum 97b632928b74c37c6b55a45d9d26a636ffb355371286a66de54923fea134f866 does not match expected value 37c6508eeaabc09b87a44a9e50d6ac854da21b2df41508dfc21ed4db7b756469
```  

I would fix it myself but I think this should be done by the maintainers or the plugin creator. @stefan-jung maybe you can have a look at that.

**Comment by jelovirt** [comment]
The plug-in metadata was created 5 years ago. I wonder what's happened there. I checked the ZIP file and the SHA256 is  `97b632928b74c37c6b55a45d9d26a636ffb355371286a66de54923fea134f866`. So the metadata should be fixed.

**Comment by stefan-jung** [comment]
Sorry, I'll fix this soon. I'm taking down the Doctales organization and move all plugin to https://gitHub.com/Stefan-Jung 

I'll fix the registry afterwards.

**Comment by pflotscher** [comment]
Thank you very much :)

**Comment by stefan-jung** [comment]
@pflotscher, I'm very sorry that I missed to follow up this on this issue. I hope you figured out/noticed that you can (since a while) find this plugin in the registry as **[org.jung.xmltask](https://www.dita-ot.org/plugins/org.jung.xmltask)**.
